### ISSUE TITLE
Increasing Threads/Pools for the Shutil obj?

### ISSUE THREAD

**Issue by lafftar** [kumaraditya303/aioshutil#3]
Hi there, i'm trying to copy some directories very quickly. I'm looking to copy about 1 directory, 1000 times, to separate folders. I'm able to do this with sync `shutil` in about 2 minutes, and `aioshutil` in about 1 minute.

**My Code:**

```py
    async def make_port_files(self):
        """
        copy all the files from base to this directory
        copytree() makes the directories needed recursively.
        """
        while True:
            try:
                await copytree(
                    src=f'{get_project_root()}/base_3proxy/3proxy/',
                    dst=self.port_directory,
                    dirs_exist_ok=True
                )
                break
            except shutil.Error:
                await self.stop_port()
                continue
```            

It's part of a class that does other things. The directory it's trying to copy is about 5MB. Is there a way to make this faster? I'll eventually need to copy thousands of files and it would help if I could go a bit quicker. Please let me know if there's anything I can do to expand on this question.

**Comment by kumaraditya303** [comment]
Hi,

You can change the default ThreadPoolExecutor to your requirement by adding this add the top of application entrypoint 

```python
import asyncio
from concurrent.futures import ThreadPoolExecutor

threads = 10
loop = asyncio.get_event_loop()

loop.set_default_executor(ThreadPoolExecutor(max_workers=threads))
```
