### ISSUE TITLE
Incorrect annotations for the wrapped functions.

### ISSUE THREAD

**Issue by mjpieters** [kumaraditya303/aioshutil#4]
You used [`cast(Awaitable[T], run_in_executor)`](https://github.com/kumaraditya303/aioshutil/blob/80982d1aa41f2e13a04cdc70cecc4a199b9a4a9d/aioshutil/__init__.py#L48) to annotate the wrapped functions, but this is unfortunately incorrect. The function objects *themselves* are not awaitable; calling the function *returns* an awaitable. The `T` generic typevar instead captures the arguments and the return value for the callable, presenting as if the functions in `aiofiles` are awaitables that produce the argument list + return value when awaited on.

The pylance type checker therefore reports an error when I use `await aioshutil.rmtree(path)`:

`Object of type "Awaitable[(path: StrOrBytesPath, ignore_errors: bool = ..., onerror: _OnErrorCallback | None = ...) -> None]" is not callable`.

Before [PEP 612](https://peps.python.org/pep-0612/) your only option was to use was a type var for the *return value only*, leaving the arguments for the callable set to `...`:

```python
T = TypeVar("T")

def sync_to_async(func: Callable[..., T]) -> Callable[..., Awaitable[T]]:
    @wraps(func)
    async def run_in_executor(*args, **kwargs) -> T:
        loop = asyncio.get_event_loop()
        pfunc = partial(func, *args, **kwargs)
        return await loop.run_in_executor(None, pfunc)

    return cast(Callable[..., Awaitable[T]], run_in_executor)
```

This would essentially turn off type checking for the _arguments_ of the wrapped function, but at least the type checker would know that there is an async function involved.

With PEP 612 having landed, you can now use the [`ParamSpec()` object](https://docs.python.org/3/library/typing.html#typing.ParamSpec), which has the added advantage of dropping the need for a cast:

```python
try:
    from typing import ParamSpec
except ImportError:
    # Python 3.9 and earlier
    from typing_extensions import ParamSpec

P = ParamSpec("P")
R = TypeVar("R")

def sync_to_async(func: Callable[P, R]) -> Callable[P, Awaitable[R]]:
    @wraps(func)
    async def run_in_executor(*args: P.args, **kwargs: P.kwargs) -> R:
        loop = asyncio.get_event_loop()
        pfunc = partial(func, *args, **kwargs)
        return await loop.run_in_executor(None, pfunc)

    return run_in_executor
```

This does require that `typing-extensions` is added as a project dependency for Python versions before 3.10:

```python
# in setup.py
    install_requires=["typing-extensions;python_version<'3.10'"],
```

I'll make a PR to fix this.

**Comment by kumaraditya303** [comment]
Thanks for the bug report and PR!
